### PR TITLE
Update Cmake petsc script

### PR DESCRIPTION
**Pull request by wenqing**
Update Cmake petsc script in order to use the latest PETSc version, 3.7.6.

### CODE REVIEW

**Comment by norihiro-w** [comment]
have you tested also with older versions, e.g. 3.5? if yes and benchmarking works, go ahead.

**Comment by bilke** [comment]
@wenqing Can you please add some note / comment where the PetSc CMake scripts come from?

**Comment by nbeyond** [comment]
82.patch works at least with compilation on Fedora Linux hydronbeyond 4.10.17-200.fc25.x86_64 (The latest version of Fedora). This is good, because petsc 3.5.4 fails in compilation on the same platform. However, the results of Kueper produces -nan. 

I am all ears for the update on this issue.

**Comment by wenqing** [comment]
@bilke Added LICENSE together with a modified README.

**Comment by wenqing** [comment]
These two benchmarks, which have nothing to do with this PR,  failed in comparison on jenkins
```
	rt1
	AT
```

**Comment by norihiro-w** [comment]
@bilke can you please merge this if it's already ready?

**Pull request merged**
