### PR TITLE
don't calculate adaptive time step size for the first time step estimation

### PR DESCRIPTION
**Pull request by norihiro-w**
needed to fix PETSc/TransLay2d benchmark

@waltherm can you please review this?

I guess the estimation with adaptive information was considered for  a case when 1st time step fails with a user-provided initial time step size. However current OGS is checking if this time step is repeated one or not, and will not call `FirstTimeStepEstimate()` anymore if it's repeated.

### CODE REVIEW

**Comment by waltherm** [comment]
@norihiro-w sure, will do after my holidays in August.

**Comment by waltherm** [comment]
@norihiro-w Looks all good, but some benchmarks are failing with this PR:

- [ ] [FEM] 	125 - UJG-HM/hm_cc_tri_s (Failed)
- [ ] [FEM] 	126 - UJG-HM/hm_dyn_tri (Failed)
- [ ] [FEM] 	128 - UJG-M/m_cc_tri_s (Failed)
- [ ] [FEM] 	129 - UJG-M/m_cc_quad_s (Failed)
- [ ] [FEM] 	135 - UJG-M/m_mises (Failed)
- [ ] [FEM] 	146 - UJG-M/creep/m_triax_lubby2 (Failed)
- [ ] [FEM] 	156 - WW-TH2M/Newton/th2m_quad (Failed)
- [ ] [FEM] 	159 - WX-M/3D_oedometer_mohr_coulomb (Failed)

How should we proceed?

**Comment by norihiro-w** [comment]
these benchmarks are nothing to do with this PR and will be fixed in the TN's PR

**Comment by waltherm** [comment]
Ok. Then :+1: & :fast_forward:

**Comment by norihiro-w** [comment]
I will merge this after running Jenkins again with the latest master. 

you need to ask Lars to get permission to merge PRs

**Pull request merged**
