### PR TITLE
Fixed reload for stress data file under MPI

### PR DESCRIPTION
**Pull request by wenqing**
as titled.

### CODE REVIEW

**Comment by norihiro-w** [comment]
hi Wenqing, can you please check why Jenkins is failing?

**Comment by norihiro-w** [comment]
and it would be helpful if you can add a benchmark testing this.

**Comment by wenqing** [comment]
@norihiro-w  Thanks for your comments.
- It sounds a jenkins' script problem. @bilke Do you have time to check this?
- I will try to add a test. Hope binary file input of the test will not cause a problem on Jenkins.

**Comment by bilke** [comment]
Yes, the Jenkins scripts aren't updated to a new syntax yet. I will fix that..

**Comment by bilke** [comment]
Should be fixed with #77.

**Comment by wenqing** [comment]
@bilke  Thanks.

**Comment by wenqing** [comment]
@norihiro-w The test for this fixing would include two sub-tests for output and a test input (reload), respectively. Because the benchmarks may run in a random order, I am not sure the test would always work.

Since there is no such test for RELOAD in the sequential version either,  I would like to merge this PR without a test. Anyway, I have already tested it with a benchmark of decovalex 2019.

**Comment by norihiro-w** [comment]
I think testing input is sufficient. If I remember it correctly, the test is already existing in some benchmark in the sequential version.

**Comment by wenqing** [comment]
@norihiro-w  I will prepare test.

**Comment by norihiro-w** [comment]
thanks!

**Comment by wenqing** [comment]
@norihiro-w  A test is added.

**Comment by norihiro-w** [comment]
thanks! if Jenkins is green, please merge it.

**Pull request merged**
